export const useSearchConfig = () => {
  const searchConfig = [
    {
      label: "Rodzaj zajęć",
      name: "activity",
      type: "select",
      options: [
        "Wspinaczka",
        "Joga",
        "Pilates",
        "Boks",
        "Crossfit",
        "Zumba",
        "Siłownia",
        "Basen",
        "Siatkówka",
        "Piłka nożna",
        "Koszykówka",
        "Badminton",
        "Tenis",
        "Squash",
        "Nordic walking",
      ],
    },
    {
      label: "Miasto",
      name: "city",
      type: "select",
      options: [
        "Warszawa",
        "Kraków",
        "Łódź",
        "Wrocław",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Katowice",
        "Białystok",
        "Gdynia",
        "Częstochowa",
        "Radom",
        "Sosnowiec",
        "Toruń",
        "Kielce",
        "Rzeszów",
        "Gliwice",
        "Zabrze",
        "Olsztyn",
        "Bielsko-Biała",
        "Bytom",
        "Zielona Góra",
      ],
    },
    {
      label: "Kiedy",
      name: "date",
      type: "date-picker",
    },
  ];
  return { searchConfig };
};
